// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';

export function ChooseFolder():Promise<bindings.Response_frontend_bindings_SelectedFolder_>;

export function ConnectToHost(arg1:string):Promise<bindings.Response_frontend_bindings_ConnectToHostResponse_>;

export function ExitHostingSession():Promise<bindings.Response_interface____>;

export function GetUsersList():Promise<bindings.Response___frontend_bindings_UserBasicInfo_>;

export function IsLoggedIn():Promise<boolean>;

export function Login(arg1:bindings.LoginRequest):Promise<bindings.Response_frontend_bindings_LoginResponse_>;

export function Logout():Promise<bindings.Response_interface____>;

export function Me():Promise<bindings.Response_frontend_bindings_Me_>;

export function RequestFilesList(arg1:Array<string>):Promise<bindings.Response_interface____>;

export function SendUpdateOnClientPath(arg1:Array<string>):Promise<void>;

export function StartHosting(arg1:bindings.StartHostingRequest):Promise<bindings.Response_interface____>;

export function StopHosting(arg1:string):Promise<bindings.Response_interface____>;
