// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFolder() {
  return window['go']['bindings']['app']['ChooseFolder']();
}

export function ConnectToHost(arg1) {
  return window['go']['bindings']['app']['ConnectToHost'](arg1);
}

export function ExitHostingSession() {
  return window['go']['bindings']['app']['ExitHostingSession']();
}

export function GetUsersList() {
  return window['go']['bindings']['app']['GetUsersList']();
}

export function IsLoggedIn() {
  return window['go']['bindings']['app']['IsLoggedIn']();
}

export function Login(arg1) {
  return window['go']['bindings']['app']['Login'](arg1);
}

export function Logout() {
  return window['go']['bindings']['app']['Logout']();
}

export function Me() {
  return window['go']['bindings']['app']['Me']();
}

export function RequestFilesList(arg1) {
  return window['go']['bindings']['app']['RequestFilesList'](arg1);
}

export function StartHosting(arg1) {
  return window['go']['bindings']['app']['StartHosting'](arg1);
}

export function StopHosting(arg1) {
  return window['go']['bindings']['app']['StopHosting'](arg1);
}
