// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function ChooseFolder():Promise<api.Response_frontend_bindings_SelectedFolder_>;

export function ConnectToHost(arg1:string):Promise<api.Response_frontend_api_ConnectToHostResponse_>;

export function ExitHostingSession():Promise<api.Response_interface____>;

export function GetUsersList():Promise<api.Response___frontend_api_UserInfoResponse_>;

export function IsLoggedIn():Promise<boolean>;

export function Login(arg1:api.LoginRequest):Promise<api.Response_frontend_api_LoginResponse_>;

export function Logout():Promise<api.Response_interface____>;

export function Me():Promise<api.Response_frontend_api_Me_>;

export function RequestFileDownload(arg1:Array<string>):Promise<api.Response_frontend_bindings_RequestFileResponse_>;

export function RequestFilesList(arg1:Array<string>):Promise<api.Response_interface____>;

export function SendUpdateOnClientPath(arg1:Array<string>):Promise<void>;

export function StartHosting(arg1:api.StartHostingRequest):Promise<api.Response_interface____>;

export function StopHosting(arg1:string):Promise<api.Response_interface____>;
