// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';

export function IsLoggedIn():Promise<boolean>;

export function Login(arg1:bindings.LoginRequest):Promise<bindings.Response_frontend_bindings_LoginResponse_>;
